service: order-processing
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: 'ap-south-1'
  memorySize: 128
  timeout: 3

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20

functions:
  healthCheck:
    handler: src/handlers/healthCheck.handler
    description: Health check endpoint
    events:
      - http:
          path: /health
          method: get
  getOrders:
    handler: src/handlers/getOrders.handler
    description: Get all orders
    events:
      - http:
          path: /orders
          method: get
  getOrderById:
    handler: src/handlers/getOrderById.handler
    description: Get order by id
    events:
      - http:
          path: /orders/{id}
          method: get
  updateOrderById:
    handler: src/handlers/updateOrderById.handler
    description: Update order by id
    events:
      - http: 
          path: /orders/{id}
          method: put
  createOrder:
    handler: src/handlers/createOrder.handler
    description: Create order
    events:
      - http:
          path: /orders
          method: post
  deleteOrderById:
    handler: src/handlers/deleteOrderById.handler
    description: Delete order by id
    events:
      - http:
          method: delete
          path: /orders/{id}

plugins:
  - serverless-esbuild